apiVersion: v1
kind: Service
metadata:
  name: register-app-service
  labels:
    app: register-app 
spec:
  selector:
    app: register-app
    
  type: LoadBalancer

  ports:
    - port: 8080
      targetPort: 8080

  